version: '3.8' ## Latest version works with Docker Engine release 18.06.0+

services:

  # Start - mongodb database definition
  ### $ mongo
  mongodb:
    image: mongo:4.2.6-bionic
    ports:
      - "27017:27017"
    healthcheck:
      test: "mongo --eval 'db.stats().ok'"
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    restart: on-failure
  # End - mongodb database definition
